/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "n64_init_isr.h"
#include "System_Clock_Slow.h"
#include "UART.h"
#include "LCD.h"
#include "uart_rx_int.h"
#include "Console_2_aliases.h"
#include "Console_2.h"
#include "n64_one_bit.h"
#include "n64_zero_bit.h"
#include "n64_ShiftReg_commack.h"
#include "N64_Shift_Clock.h"
#include "n64_ShiftReg_buttonstate.h"
#include "n64_comm_state_isr.h"
#include "count_time_to_transmit.h"
#include "Timer_1.h"
#include "Timer_2.h"
#include "UART_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

